# Generated by Django 3.2.23 on 2024-01-31 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userapp',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('emailId', models.EmailField(max_length=254)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='transcations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_emailId', models.EmailField(max_length=254)),
                ('receiver_emailId', models.EmailField(max_length=254)),
                ('transcation_status', models.CharField(max_length=2)),
                ('Amount', models.BigIntegerField(default=None, editable=False)),
                ('payment_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet_management.userapp')),
            ],
        ),
        migrations.CreateModel(
            name='otpauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_otp', models.CharField(max_length=4)),
                ('signin_otp', models.CharField(max_length=4)),
                ('login_at', models.DateTimeField(auto_now=True)),
                ('created_At', models.DateTimeField(auto_now=True)),
                ('verified_status', models.BooleanField(blank=True, default=False, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet_management.userapp')),
            ],
        ),
        migrations.CreateModel(
            name='balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField(default=None, editable=False)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wallet_management.userapp')),
            ],
        ),
    ]
